export const SKIP_DIRS = new Set([
  "node_modules",
  ".git",
  "dist",
  "build",
  "__pycache__",
  ".next",
  ".nuxt",
  "vendor",
  "target",
  ".terraform",
  "coverage",
  ".pytest_cache",
  ".mypy_cache",
]);

export const SKIP_EXTENSIONS = new Set([
  ".lock",
  ".png",
  ".jpg",
  ".jpeg",
  ".gif",
  ".svg",
  ".ico",
  ".woff",
  ".woff2",
  ".ttf",
  ".eot",
  ".mp4",
  ".mp3",
  ".zip",
  ".tar",
  ".gz",
  ".pdf",
  ".exe",
  ".dll",
  ".so",
  ".dylib",
  ".pyc",
  ".pyo",
  ".class",
  ".o",
  ".a",
  ".map",
]);

export const MANIFEST_FILES = new Set([
  "package.json",
  "requirements.txt",
  "setup.py",
  "setup.cfg",
  "pyproject.toml",
  "pom.xml",
  "build.gradle",
  "build.gradle.kts",
  "go.mod",
  "Gemfile",
  "Cargo.toml",
  "composer.json",
]);

export const MANIFEST_EXTENSIONS = new Set([".csproj", ".fsproj", ".sln"]);

export const ROUTE_DIRS = new Set([
  "routes",
  "controllers",
  "handlers",
  "api",
  "views",
  "endpoints",
  "routers",
]);

export const MAIN_FILE_NAMES = new Set([
  "main.py",
  "app.py",
  "server.py",
  "index.ts",
  "index.js",
  "app.ts",
  "app.js",
  "server.ts",
  "server.js",
  "main.go",
  "main.rs",
  "Main.java",
  "Application.java",
  "Program.cs",
  "Startup.cs",
  "main.rb",
  "app.rb",
  "config.ru",
]);

export const CONFIG_FILE_NAMES = new Set([
  "Dockerfile",
  "docker-compose.yml",
  "docker-compose.yaml",
  "otel-collector-config.yaml",
  ".env.example",
]);

export const STACK_SIGNATURES: Record<string, Record<string, string>> = {
  "package.json": {
    express: "Node.js / Express",
    fastify: "Node.js / Fastify",
    next: "Node.js / Next.js",
    nuxt: "Node.js / Nuxt",
    nestjs: "Node.js / NestJS",
    "@hapi": "Node.js / Hapi",
    koa: "Node.js / Koa",
    react: "JavaScript / React",
    vue: "JavaScript / Vue",
    angular: "TypeScript / Angular",
  },
  "requirements.txt": {
    django: "Python / Django",
    flask: "Python / Flask",
    fastapi: "Python / FastAPI",
    starlette: "Python / Starlette",
    tornado: "Python / Tornado",
    celery: "Python / Celery",
  },
  "pyproject.toml": {
    django: "Python / Django",
    flask: "Python / Flask",
    fastapi: "Python / FastAPI",
  },
  "go.mod": {
    "gin-gonic": "Go / Gin",
    "gorilla/mux": "Go / Gorilla Mux",
    "labstack/echo": "Go / Echo",
    fiber: "Go / Fiber",
    "net/http": "Go",
  },
  Gemfile: {
    rails: "Ruby / Rails",
    sinatra: "Ruby / Sinatra",
  },
  "pom.xml": {
    "spring-boot": "Java / Spring Boot",
    quarkus: "Java / Quarkus",
    micronaut: "Java / Micronaut",
  },
  "build.gradle": {
    "spring-boot": "Java / Spring Boot",
    ktor: "Kotlin / Ktor",
  },
  "Cargo.toml": {
    actix: "Rust / Actix",
    axum: "Rust / Axum",
    rocket: "Rust / Rocket",
  },
};

export const LANGUAGE_MAP: Record<string, string> = {
  ".py": "python",
  ".js": "javascript",
  ".ts": "typescript",
  ".tsx": "tsx",
  ".jsx": "jsx",
  ".go": "go",
  ".java": "java",
  ".rb": "ruby",
  ".rs": "rust",
  ".cs": "csharp",
  ".kt": "kotlin",
  ".scala": "scala",
  ".yml": "yaml",
  ".yaml": "yaml",
  ".json": "json",
  ".toml": "toml",
  ".xml": "xml",
  ".sql": "sql",
  ".sh": "bash",
  ".dockerfile": "dockerfile",
  ".tf": "hcl",
  ".proto": "protobuf",
};
